config/routes.rb
PostitTemplate::Application.routes.draw do
  root to: 'posts#index'

  get '/register', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  get '/pin', to: 'sessions#pin'
  post '/pin', to: 'sessions#pin'

  resources :users, only: [:create, :edit, :update, :show]
  resources :categories, except: [:destroy]
  resources :posts, except: [:destroy] do
    member do
      post :vote
    end

    resources :comments, only: [:create] do
      member do
        post :vote
      end
    end
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
  include VoteableIan
  include Sluggable

  belongs_to :creator, foreign_key: 'user_id', class_name: 'User'
  has_many :comments
  has_many :post_categories
  has_many :categories, through: :post_categories

  validates :title, presence: true, length: {minimum: 5}
  validates :url, presence: true
  validates :description, presence: true

  sluggable_column :title
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :vote]
  before_action :require_user, except: [:index, :show]
  before_action :require_creator, only: [:edit, :update]
  #1. setup an instance variable for action
  #2. redirect away from an action

  def index
    @posts = Post.all.sort_by{|x| x.total_votes}.reverse

    respond_to do |format|
      format.html
      format.json { render json: @posts }
      format.xml {render xml: @posts }
    end
  end

  def show
    @comment = Comment.new

    respond_to do |format|
      format.html
      format.json { render json: @post }
      format.xml {render xml: @post }
    end
  end

  def vote
    @vote = Vote.create(voteable: @post, creator: current_user, vote: params[:vote])

    respond_to do |format|
      format.html do
        if vote.valid?
          flash[:notice] = "Your vote has been counted"
        else
          flash[:error] = "Vote denied"
        end
        redirect_to :back
      end
      format.js
    end
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.creator = current_user

    if @post.save
      flash[:notice] = "Your post was created."
      redirect_to posts_path
    else
      render :new
    end

  end

  def edit; end

  def update
    if @post.update(post_params)
      flash[:notice] = "The post was updated"
      redirect_to posts_path
    else
      render :edit
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :url, :description, category_ids: [])
  end

  def set_post
    @post = Post.find_by(slug: params[:id])
  end

  def require_creator
   access_denied unless logged_in? and (current_user == @post.creator || current_user.admin?)
  end

end

app/views/posts/_form.html.erb
<%= render "shared/errors", obj: @post %>

<div class="well">
  <%= form_for @post do |f| %> 
    <div class="control-group">
      <%= f.label :title, "Title" %>
      <%= f.text_field :title %>
    </div>
    <div class="control-group">
      <%= f.label :url, "URL" %>
      <%= f.text_field :url %>
    </div>
    <div class="control-group">
      <%= f.label :description, "Description" %>
      <%= f.text_area :description, rows: 5 %>
    </div>

    <div class="control-group">
      <%= f.label "Categories" %>
      <%= f.collection_check_boxes :category_ids , Category.all, :id, :name do |cb| %>
      <% cb.label(class: "checkbox inline") {cb.check_box(class: "checkbox") + cb.text} %>
      <% end %>
    </div>

    <%= f.submit button, class: "btn btn-primary" %>
  <% end %>
</div> 

app/views/posts/_post.html.erb
<div class="row">
  <div class="span0 well text-center">
    <% if logged_in? %>
      <%= link_to vote_post_path(post, vote: true), method: 'post', remote: true do %>
        <i class="icon-arrow-up"></i>
      <% end %>
    </br>
    <% end %>
    <span id='post_<%=post.slug%>_votes'><%= "#{post.total_votes} Votes" %></span>
    </br>
    <% if logged_in? %>
      <%= link_to vote_post_path(post, vote: false), method: 'post', remote: true do %>
        <i class="icon-arrow-down"></i>
      <% end %>
    <% end %>
  </div>
  <div class="span8 well">
    <%= render post.categories %>
    <div class="post_title_url" target="_blank">
      <h4><%= link_to post.title, fix_url(post.url), :target => "_blank" %></h4>
    </div>
    <p><%= simple_format(post.description) %></p>
      <span class="quiet">posted by </span><%= link_to("#{post.creator.username}", user_path(post.creator)) %>
      <small>at <%= date_time(post.created_at) %></small>
    </p>
    <small>
    <span>
      <%= link_to("#{post.comments.size} comments", post_path(post)) %>
    </span>
    </small>
  </div>
</div>

app/views/posts/edit.html.erb
<%= render "shared/content_title", title: "Edit post" %>

<%= render "form", button: "Update Post" %>

app/views/posts/index.html.erb
<%= render 'shared/content_title', title: "All Posts" %>

<% @posts.each do |post| %>
  <%= render "post", post: post %>
<% end %>

app/views/posts/new.html.erb
<%= render "shared/content_title", title: "Create a new post" %>

<%= render "form", button: "Create Post" %>

app/views/posts/show.html.erb
<% if logged_in? && @post.user_id == current_user.id || logged_in? && current_user.admin? %>
  <p class="pull-right">
    [<%= link_to "edit this post", edit_post_path(@post)%>]
  </p>
<% end %>

<p>
  <%= render @post.categories %>
</p>

<%= render 'shared/content_title', title: @post.title %>

<p>
  <%= simple_format(@post.description) %>
</p>
<hr/>
<% if logged_in? %>
  <h5>Leave a Comment:</h5>
  <%= form_for [@post, @comment] do |f| %>
    <div class="row">
      <%= render 'shared/errors', obj: @comment %>
    </div>
    <div class="control-group">
      <% f.label :body %>
      <%= f.text_area :body, rows: 3, class: 'span4' %>
    </div>
    <%= f.submit "Create Comment", class: "btn btn-primary" %>
  <% end %>
<% end %>

<h5>Comments:</h5>
<% @post.comments.each do |comment| %>
  <%= render 'comments/comment', comment: comment %>
<% end %>

app/views/posts/vote.js.erb
<% if @vote.valid? %>
  $('#post_<%= @post.slug %>_votes').html('<%= @post.total_votes %> Votes');
<% else %>
  alert('You can only vote on a post once');
<% end %>