config/routes.rb
PostitTemplate::Application.routes.draw do
  root to: 'posts#index'

  get '/register', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  get '/pin', to: 'sessions#pin'
  post '/pin', to: 'sessions#pin'

  resources :users, only: [:create, :edit, :update, :show]
  resources :categories, except: [:destroy]
  resources :posts, except: [:destroy] do
    member do
      post :vote
    end

    resources :comments, only: [:create] do
      member do
        post :vote
      end
    end
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
  include Sluggable

  has_many :post_categories
  has_many :posts, through: :post_categories

  validates :name, presence: true, uniqueness: true

  sluggable_column :name
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
before_action :set_category, only: [:show, :edit, :update]
before_action :require_user, only: [:new, :edit, :update]
before_action :require_admin, only: [:new, :edit, :update]

def index
  @categories = Category.all
  # @category_id = Category.find(params[:id]).category_id
end

def show; end

def new
  @category = Category.new
end

def create
  @category = Category.new(category_params)

  if @category.save
    flash[:notice] = "Category created"
    redirect_to categories_path
  else
    render :new
  end
end

# def edit; end

# def update
#   if @category.update(category_params)
#     flash[:notice] = "Category was updated"
#     redirect_to categories_path
#   else
#     render :edit
#   end
# end

private

  def category_params
    params.require(:category).permit(:name)
  end

  def set_category
    @category = Category.find_by(slug: params[:id])
  end

end

app/views/categories/_category.html.erb
<span class="badge"><%= link_to category.name, category_path(category) %></span>

app/views/categories/_form.html.erb
<%= render "shared/errors" , obj: @category %>

<div class="well">
  <%= form_for @category do |f| %> 
    <div class="control-group">
      <%= f.label :name, "Category Name" %>
      <%= f.text_field :name %>
    </div>
    <%= f.submit button, class: "btn btn-primary" %>
  <% end %>
</div>

app/views/categories/index.html.erb
<%= render 'shared/content_title', title: "All Categories" %>

<div class="row">
  <div class="span8 well">
    <% if logged_in? && current_user.admin? %>
      <%= link_to 'New Category +', new_category_path, class: 'btn' %>
    <% end %>
    <ul>
      <% @categories.each do |category| %>
      <h4><li><%= link_to("#{category.name} (#{category.posts.size})", category_path(category))%></li></h4>
      <% end %>
    </ul>
  </div>
</div>

app/views/categories/new.html.erb
<%= render "shared/content_title", title: "Create a new category" %>

<%= render "form", button: "Create Category" %>

app/views/categories/show.html.erb
<% header = link_to("All Posts", posts_path) + "&raquo; #{@category.name}".html_safe %>

<%= render 'shared/content_title', title: header %>

<% @category.posts.each do |post| %>
<%= render "posts/post", post: post %>
<% end %>